name: cs2_simulator
description: "Counter-Strike 2 case opening and Trade-Up contract creation simulator written in Flutter + Dart."
publish_to: 'none'

version: 0.7.0

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  image: ^4.2.0

flutter_launcher_icons:
  image_path: assets/app_icon/latest_case.png

  android: true
  adaptive_icon_background: assets/app_icon/transparent_bg.png
  adaptive_icon_foreground: assets/app_icon/latest_case_foreground.png
  adaptive_icon_monochrome: assets/app_icon/latest_case_monochrome.png
  adaptive_icon_foreground_inset: 18

  ios: true
  remove_alpha_ios: false
  image_path_ios_dark_transparent: assets/app_icon/latest_case_ios_dark.png
  image_path_ios_tinted_grayscale: assets/app_icon/latest_case_ios_tinted.png
  desaturate_tinted_to_grayscale_ios: false

  macos:
    generate: true
    image_path: assets/app_icon/latest_case.png

  windows:
    generate: true
    image_path: assets/app_icon/latest_case.png
    icon_size: 256

  linux: true

  web:
    generate: true
    image_path: assets/app_icon/latest_case.png
    background_color: "#00000000"
    theme_color: "#00000000"

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/skins/
    - assets/cases/
    - assets/reward_collections/
    - assets/operation_collections/
    - assets/tournament_logos/
